# Generated by Django 3.2.16 on 2022-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_content', models.CharField(max_length=200)),
                ('whatsnew', models.CharField(max_length=200)),
                ('download_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IosVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('force_update', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_content', models.CharField(max_length=200)),
                ('whatsnew', models.CharField(max_length=200)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('is_customer_app', models.BooleanField(default=False)),
                ('is_delivery_boy_app', models.BooleanField(default=False)),
            ],
        ),
    ]
