# Generated by Django 3.2.16 on 2022-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidversion',
            name='is_customer_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='androidversion',
            name='is_delivery_boy_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='androidversion',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
