# Generated by Django 3.2.16 on 2022-12-12 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_subzone'),
        ('accounts', '0003_employee_employeecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('followed_store', models.ManyToManyField(blank=True, null=True, related_name='customer_infos', to='partner.Partner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
