# Generated by Django 3.2.16 on 2023-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('REJECTE', 'Rejected')], max_length=50, null=True),
        ),
    ]
