# Generated by Django 3.2.16 on 2023-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230109_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('REJECTED', 'Rejected')], max_length=50, null=True),
        ),
    ]
