# Generated by Django 3.2.16 on 2022-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20221112_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
    ]
