# Generated by Django 3.2.16 on 2022-11-18 17:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_alter_partner_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='longitude',
        ),
        migrations.AddField(
            model_name='zone',
            name='address',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.CharField(default='Dhaka', max_length=50),
        ),
        migrations.AddField(
            model_name='zone',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
