# Generated by Django 3.2.16 on 2022-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_subzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OTHERS', 'Others')], default='OTHERS', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_third_party_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_third_party_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
