# Generated by Django 3.2.16 on 2022-11-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_alter_partner_zone'),
        ('catalogue', '0031_auto_20221112_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partner.zone'),
        ),
    ]
