# Generated by Django 3.2.16 on 2022-12-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_subzone'),
        ('catalogue', '0032_product_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='partner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='partner.partnertype'),
        ),
    ]
