# Generated by Django 3.2.16 on 2022-12-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_category_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='zone',
        ),
    ]
