# Generated by Django 3.2.16 on 2022-12-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_remove_product_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='Offer')),
                ('schedule_type', models.CharField(blank=True, choices=[('Time_Wise', 'Time wise'), ('Date_Wise', 'Date wise')], default='Date_wise', max_length=50, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Amount')], default='PERCENTAGE', max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('promo_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'percentage'), ('AMOUNT', 'amount')], max_length=50, null=True)),
                ('max_purchase_amount', models.FloatField(default=0)),
                ('minimum_purchase_amount', models.FloatField(default=0)),
                ('minimum_applied', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
