# Generated by Django 3.2.16 on 2022-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20221220_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Time_Wise', 'Time wise'), ('Date_Wise', 'Date wise')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
