# Generated by Django 3.2.16 on 2022-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20221220_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Offer'),
        ),
    ]
