# Generated by Django 3.2.16 on 2022-11-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_subzone'),
        ('accounts', '0001_initial'),
        ('order', '0019_orderreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('others', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=25)),
                ('return_counter', models.IntegerField(default=0)),
                ('return_log', models.JSONField(blank=True, null=True)),
                ('delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_events', to='accounts.deliveryman')),
                ('return_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_events', to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCountPerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_count_per_schedules', to='partner.partner')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_count_per_schedules', to='order.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_count_per_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.ordercountperschedule'),
        ),
    ]
