# Generated by Django 3.2.16 on 2022-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20221121_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreturn',
            old_name='oder',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Success', 'Success'), ('Failed', 'Failed')], max_length=10, null=True),
        ),
    ]
