# Generated by Django 3.2.16 on 2022-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20221127_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('ACCEPT', 'Accept'), ('REFUND', 'Refund'), ('CHANGE_PRODUCT', 'Change Product'), ('PARTNER_REJECTED', 'Partner Rejected'), ('ACCEPT', 'Accept'), ('SUCCESS', 'Success')], max_length=100, null=True),
        ),
    ]
