# Generated by Django 3.2.16 on 2023-01-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_alter_discount_image'),
        ('order', '0023_auto_20221231_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalogue.promocode'),
        ),
    ]
